const taskExamples = [
  {
    id: "task-1",
    title: "Build Hoichoi Kanban Board",
    description: "Design and develop a responsive Kanban board for managing Hoichoi tasks, workflows, and project activities.",
    priority: "high",
    assignee: "Rudra Karmakar",
    status: "in-progress",
    type: "story",
    position: 0,
  },
  {
    id: "task-2",
    title: "Refine empty states",
    description: "Give each empty view a useful next step instead of a dead end.",
    priority: "medium",
    assignee: "Theo Adams",
    status: "todo",
    type: "task",
    position: 0,
  },
  {
    id: "task-3",
    title: "Audit keyboard navigation",
    description: "Check focus order and accessible labels across the main workspace.",
    priority: "low",
    assignee: "Maya Chen",
    status: "backlog",
    type: "defect",
    position: 0,
  },
  {
    id: "task-4",
    title: "Ship activity timeline",
    description:
      "Connect the timeline to the latest task events and add a compact timestamp.",
    priority: "high",
    assignee: "Jordan Lee",
    status: "done",
    type: "task",
    position: 0,
  },
  {
    id: "task-5",
    title: "Prepare release notes",
    description: "Summarize the improvements that are ready for the next release.",
    priority: "medium",
    assignee: "Jordan Lee",
    status: "backlog",
    type: "story",
    position: 1,
  },
  {
    id: "task-6",
    title: "Fix filter state reset bug",
    description: "The assignee filter fails to reset when switching views.",
    priority: "high",
    assignee: "Maya Chen",
    status: "todo",
    type: "defect",
    position: 1,
  },
];

module.exports = { taskExamples };
